from __future__ import annotations

import json
from pathlib import Path

from openpyxl import load_workbook


ROOT = Path(__file__).resolve().parents[2]
OUTPUT_PATH = ROOT / "web_static" / "src" / "baseline-data.js"

FINANCE_DIR = Path(r"E:\桌面\李想\财务报表")
REPORT_DIR = Path(r"E:\桌面\李想\三张表")

SOURCE_25 = FINANCE_DIR / "2025 monthly Renta DW _ DEC_ACT.xlsx"
SOURCE_BUDGET = FINANCE_DIR / "Budget DW Cost 26_Monthly(1) (1).xlsx"
SOURCE_4PLUS8 = FINANCE_DIR / "4+8【最新】制造费用累计-大厨电（每月更新）-2026(3).xlsx"
SOURCE_REPORT = REPORT_DIR / "Candy洗碗机三张表-5.26.xlsx"

RENTA_2025_MONTH_VALUE_COLS = {month: 8 + (month - 1) * 3 for month in range(1, 13)}

SUMMARY_LABELS = {
    "CS_DEPRECIATION": "折旧（含FC）",
    "CS_DIRECT LABOUR": "直接人工",
    "CS_DIRECT LABOR": "直接人工",
    "CS_SCRAP_VARIABLE": "可回收废料",
    "CS_FIX COST": "运营费",
    "CS_VARIABLE COST": "生产耗用品",
    "CS_OBSOLESCENCE": "存货跌价准备",
    "CS_RESELLING": "废品回收",
    "CS_FIX UTILITIES": "固定能源费",
    "CS_VARIABLE UTILITIES": "变动能源费",
    "CS_INDIRECT LABOUR": "间接人工成本-辅助人员",
    "CS_INDIRECT LABOR": "间接人工成本-辅助人员",
    "CS_FIXED LABOUR": "固定人工-白领",
    "CS_FIXED LABOR": "固定人工-白领",
    "CS_SEMIFIX": "半固定-班车/工作服",
    "CS_OVH_ADM": "分摊费用",
}


def main() -> None:
    payload = {
        "baseline25ByMonth": extract_2025_actuals(),
        "budget26ByMonth": extract_budget_accounts(),
        "forecast4plus8ByMonth": extract_4plus8_forecast(),
        "monthNarratives": extract_month_narratives(),
        "categoryOrder": extract_category_order(),
    }
    payload["accountInfo"] = pack_account_info(payload)
    content = (
        "// Generated by web_static/scripts/build-baseline-data.py.\n"
        "// Sources: 2025 Renta actual, 2026 budget, latest 4+8 forecast, and Candy monthly narratives.\n"
        f"export const MODEL_DATA = {json.dumps(payload, ensure_ascii=False, separators=(',', ':'))};\n\n"
        "export const BASELINE_25_BY_MONTH = MODEL_DATA.baseline25ByMonth;\n"
        "export const BUDGET_26_BY_MONTH = MODEL_DATA.budget26ByMonth;\n"
        "export const FORECAST_4PLUS8_BY_MONTH = MODEL_DATA.forecast4plus8ByMonth;\n"
        "export const MONTH_NARRATIVES = MODEL_DATA.monthNarratives;\n"
        "export const CATEGORY_ORDER = MODEL_DATA.categoryOrder;\n"
        "export const ACCOUNT_INFO = MODEL_DATA.accountInfo;\n"
        "export const BASELINE_25_ACCOUNTS = MODEL_DATA.baseline25ByMonth[1].accounts;\n"
        "export const REFERENCE_4PLUS8 = MODEL_DATA.forecast4plus8ByMonth;\n"
    )
    OUTPUT_PATH.write_text(content, encoding="utf-8")
    print(OUTPUT_PATH)
    print("25 month account counts:", {m: len(v["accounts"]) for m, v in payload["baseline25ByMonth"].items()})
    print("budget month account counts:", {m: len(v["accounts"]) for m, v in payload["budget26ByMonth"].items()})


def extract_2025_actuals() -> dict[int, dict]:
    wb = load_workbook(SOURCE_25, read_only=True, data_only=True)
    ws = sheet_by_contains(wb, "Renta DW _2025")
    result = {}
    for month in range(1, 13):
        value_col = RENTA_2025_MONTH_VALUE_COLS[month]
        cpu_col = value_col + 1
        volume = number(ws.cell(1, value_col).value)
        accounts = []
        categories = {}
        for row in range(4, ws.max_row + 1):
            code = account_code(ws.cell(row, 2).value)
            if not code:
                continue
            amount = number(ws.cell(row, value_col).value)
            unit = number(ws.cell(row, cpu_col).value)
            key = summary_key(ws.cell(row, 5).value)
            category = SUMMARY_LABELS.get(key, "其他制造费")
            accounts.append([code, text(ws.cell(row, 3).value), category, key, amount, unit if unit is not None else calc_unit(amount, volume)])
            categories[category] = categories.get(category, 0) + (amount or 0)
        result[month] = {
            "month": month,
            "volume": volume,
            "accounts": accounts,
            "categories": [{"label": k, "amount25": v} for k, v in categories.items()],
        }
    wb.close()
    return result


def extract_budget_accounts() -> dict[int, dict]:
    wb = load_workbook(SOURCE_BUDGET, read_only=True, data_only=True)
    ws = wb.worksheets[0]
    result = {}
    for month in range(1, 5):
        value_col = 4 + month
        volume = number(ws.cell(1, value_col).value)
        accounts = []
        categories = {}
        for row in range(5, ws.max_row + 1):
            if text(ws.cell(row, 1).value).upper() != "YES":
                continue
            code = account_code(ws.cell(row, 2).value)
            if not code:
                continue
            amount = number(ws.cell(row, value_col).value)
            key = summary_key(ws.cell(row, 4).value)
            category = SUMMARY_LABELS.get(key, "其他制造费")
            accounts.append([code, text(ws.cell(row, 3).value), category, key, amount, calc_unit(amount, volume)])
            categories[category] = categories.get(category, 0) + (amount or 0)
        result[month] = {
            "month": month,
            "volume": volume,
            "accounts": accounts,
            "categories": [{"label": k, "amountBudget": v} for k, v in categories.items()],
        }
    wb.close()
    return result


def extract_4plus8_forecast() -> dict[int, dict]:
    wb = load_workbook(SOURCE_4PLUS8, read_only=True, data_only=True)
    ws = wb.worksheets[2]
    result = {}
    for month in range(1, 5):
        col = 3 + month
        categories = []
        for row in range(80, 96):
            label = text(ws.cell(row, 3).value)
            if not label or label in {"合计", "单台"}:
                continue
            categories.append({"label": label, "amountForecast": number(ws.cell(row, col).value)})
        result[month] = {
            "month": month,
            "volume": number(ws.cell(79, col).value),
            "total": number(ws.cell(96, col).value),
            "unit": number(ws.cell(97, col).value),
            "categories": categories,
        }
    wb.close()
    return result


def extract_month_narratives() -> dict[int, dict]:
    wb = load_workbook(SOURCE_REPORT, read_only=True, data_only=True)
    result = {}
    for month in range(1, 5):
        ws = sheet_by_contains(wb, f"洗碗机{month}月")
        blocks = []
        for row in range(1, min(ws.max_row, 6) + 1):
            for col in range(1, min(ws.max_column, 4) + 1):
                value = clean_report_text(ws.cell(row, col).value)
                if value and ("总结" in value or "原因" in value or "变动" in value):
                    blocks.append(value)
        result[month] = {"month": month, "blocks": blocks}
    wb.close()
    return result


def extract_category_order() -> list[str]:
    wb = load_workbook(SOURCE_4PLUS8, read_only=True, data_only=True)
    ws = wb.worksheets[2]
    order = []
    for row in list(range(80, 96)) + list(range(105, 122)):
        label = text(ws.cell(row, 3).value)
        if label and label not in {"合计", "单台"} and label not in order:
            order.append(label)
    wb.close()
    return order


def pack_account_info(payload: dict) -> dict[str, list[str]]:
    info = {}
    for section, amount_key, unit_key in [
        ("baseline25ByMonth", "amount25", "unit25"),
        ("budget26ByMonth", "amountBudget", "unitBudget"),
    ]:
        for month_data in payload[section].values():
            packed = []
            for account in month_data["accounts"]:
                code, desc, category, key, amount, unit = account
                if code not in info:
                    info[code] = [desc, category, key]
                packed.append([code, amount, unit])
            month_data["accounts"] = packed
    return info


def sheet_by_contains(wb, name_part: str):
    for ws in wb.worksheets:
        if name_part.strip() in ws.title.strip():
            return ws
    raise KeyError(name_part)


def text(value) -> str:
    if value is None:
        return ""
    return str(value).replace("\u3000", " ").strip()


def clean_report_text(value) -> str:
    return text(value).replace("_x000b_", "\n").replace("\r\n", "\n")


def summary_key(value) -> str:
    label = text(value)
    if label.startswith("*"):
        label = label.lstrip("*").strip()
    return label.upper()


def account_code(value) -> str:
    if value is None:
        return ""
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float) and value.is_integer():
        return str(int(value))
    raw = str(value)
    import re

    match = re.search(r"(\d{10}|\d{6})", raw)
    return match.group(1) if match else ""


def number(value):
    if value is None or value == "":
        return None
    if isinstance(value, (int, float)):
        return float(value)
    try:
        return float(str(value).replace(",", ""))
    except ValueError:
        return None


def calc_unit(amount, volume):
    if amount is None or not volume:
        return None
    return amount / volume * 1000


if __name__ == "__main__":
    main()
